export function creatTemplate() {
  const TITLE = 'Minesweeper';
  const SMALL = 'easy - 10x10';
  const MEDIUM = 'medium - 15x15';
  const HARD = 'hard - 25x25';
  const LABEL = 'Mines';
  const body = document.querySelector('body');
  const container = document.createElement('main');
  container.className = 'main';
  const wrapper = document.createElement('section');
  wrapper.className = 'wrapper';
  const titleGame = document.createElement('h1');
  titleGame.className = 'title';
  titleGame.textContent = TITLE;
  const settings = document.createElement('div');
  settings.className = 'settings';
  const labelMines = document.createElement('label');
  labelMines.className = 'label-mines';
  labelMines.textContent = LABEL;
  labelMines.setAttribute('for', 'quantity-mines');
  const quantityMines = document.createElement('input');
  quantityMines.className = 'quantity-mines';
  quantityMines.type = 'number';
  quantityMines.id = 'quantity-mines';
  quantityMines.setAttribute('min', '10');
  quantityMines.setAttribute('max', '99');
  quantityMines.setAttribute('placeholder', 'Default 10"');
  const size = document.createElement('select');
  size.className = 'size';
  const smallSize = document.createElement('option');
  smallSize.className = 'smallSize';
  smallSize.textContent = SMALL;
  smallSize.value = 10;
  const mediumSize = document.createElement('option');
  mediumSize.className = 'mediumSize';
  mediumSize.textContent = MEDIUM;
  mediumSize.value = 15;
  const hardSize = document.createElement('option');
  hardSize.className = 'hardSize';
  hardSize.textContent = HARD;
  hardSize.value = 25;
  const statusGame = document.createElement('div');
  statusGame.className = 'status-game';
  const amountMines = document.createElement('span');
  amountMines.className = 'amount mines';
  const emoji = document.createElement('button');
  emoji.className = 'emoji happy';
  const amountTimes = document.createElement('span');
  amountTimes.className = 'amount times';
  const playground = document.createElement('div');
  playground.className = 'playground';

  statusGame.append(amountMines);
  statusGame.append(emoji);
  statusGame.append(amountTimes);
  wrapper.append(titleGame);
  size.append(smallSize);
  size.append(mediumSize);
  size.append(hardSize);
  settings.append(labelMines);
  settings.append(quantityMines);
  settings.append(size);
  wrapper.append(settings);
  wrapper.append(statusGame);
  wrapper.append(playground);
  container.append(wrapper);
  body.append(container);
  return body;
}
