import { Constants, Help } from '../types';
import highlightElement from './highlight';

export default function renderHelp(help: Help): HTMLElement {
  const helpWrapper: HTMLElement = document.createElement('div');
  helpWrapper.className = 'help__wrapper';
  const helpSelector: HTMLElement = document.createElement('h3');
  helpSelector.className = 'help__selector';
  helpSelector.textContent = `${help.selector}`;
  const helpTitle: HTMLElement = document.createElement('h4');
  helpTitle.className = 'help__title';
  helpTitle.textContent = `${help.title}`;
  const helpSyntax: HTMLElement = document.createElement('p');
  helpSyntax.className = 'help__syntax';
  helpSyntax.textContent = `${help.syntax}`;
  const helpDescription: HTMLElement = document.createElement('p');
  helpDescription.className = 'help__description';
  helpDescription.textContent = `${help.description}`;
  const helpExampleTitle: HTMLElement = document.createElement('h3');
  helpExampleTitle.className = 'help__title help__title_example';
  helpExampleTitle.textContent = `${Constants.examplesTitle}`;
  const helpExamples: HTMLElement = document.createElement('p');
  helpExamples.className = 'help__examples';
  helpExamples.textContent = `${help.examples}`;
  const helpUse: HTMLElement = document.createElement('p');
  helpUse.className = 'help__use';
  helpUse.textContent = `${Constants.useHelp}`;
  const helpButton: HTMLElement = document.createElement('button');
  helpButton.className = 'help__button buttons buttons_aside';
  helpButton.textContent = `Help`;
  highlightElement(helpSyntax);
  highlightElement(helpExamples);
  helpWrapper.append(helpSelector);
  helpWrapper.append(helpTitle);
  helpWrapper.append(helpSyntax);
  helpWrapper.append(helpDescription);
  helpWrapper.append(helpExampleTitle);
  helpWrapper.append(helpExamples);
  helpWrapper.append(helpUse);
  helpWrapper.append(helpButton);
  return helpWrapper;
}
