import createTemplate from '../template';

const bodyEx: HTMLBodyElement = document.createElement('body');
if (bodyEx) bodyEx.className = 'body';
bodyEx.innerHTML = `<body class="body"><main class="main"><section class="playground"><header class="header" /><h1 class="task">Select all the plates</h1><section class="table"><div class="table__top"><plate class="plate"><fruits class="pear selected" /></plate><plate class="plate selected" id="dark" /></div><div class="table__legs" /></section><section class="playground__interection interection"><section class="interection__editor editor"><div class="interection__header"><h3 class="interection__title">CSS Editor</h3><h4 class="interection__file">style.css</h4></div><div class="interection__container container"><div class="container__numbers editor__numbers">1<br />2<br />3<br />4<br />5<br />6<br />7<br />8<br />9<br />10<br />11<br />12<br />13<br />14<br />15<br />16<br />17<br />18<br />19<br />20</div><div class="container__field editor__field"><form class="editor__form form"><input class="form__input" id="solution" placeholder="Type in a 
CSS selector" type="text" /><input class="form__button" type="submit" value="enter" /></form><div class="editor__description">{<br />/* Styles would go here. */<br />}</div><div class="editor__help"><br />/* <br />Type "help" to show answer. <br />*/</div><div class="editor__skip"><br />/* <br />Type a number to skip to a level.<br />Ex → "5" for level 5 
<br />*/</div></div></div></section><section class="interection__viewer viewer"><div class="interection__header"><h3 class="interection__title">HTML Viewer</h3><h4 class="interection__file">table.html</h4></div><div class="interection__container container"><div class="container__numbers viewer__numbers">1<br />2<br />3<br />4<br />5<br />6<br />7<br />8<br />9<br />10<br />11<br />12<br />13<br />14<br />15<br />16<br />17<br />18<br />19<br />20</div><div class="container__field viewer__field"><div class="viewer__markup markup"><div class=".markup__header">&lt;div class="table"&gt;</div><div class="markup__element">&lt;plate class="plate" /&gt;<div class="markup__element">&lt;fruits class="pear" /&gt;</div></div><div class="markup__element">&lt;plate class="plate" id="dark" /&gt;</div><div class=".markup__header">&lt;/div&gt;</div></div></div></div></section></section></section><aside class="aside"><h2 class="aside__title">Choose a level</h2><a class="level" id="1"><span class="level__check" /><span class="level__id">1</span><span class="level__name">Plates</span></a><a class="level" id="2"><span class="level__check" /><span class="level__id">2</span><span class="level__name">Fruits</span></a></aside></main><footer class="footer" /></body>`;
test('Template has been created', () => {
  expect(createTemplate()).toStrictEqual(bodyEx);
});
